services:
  - type: web
    name: mp3downloader-server
    runtime: docker
    repo: https://github.com/listamigo/mp3-descargas
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8899
    healthCheckPath: /api/health
